import nextEnv from '@next/env';
import { neon,Pool as NeonPool,neonConfig } from '@neondatabase/serverless';
import assert from 'node:assert/strict';
import { db,fecharDb } from '../src/lib/db';
import { PDFDocument } from 'pdf-lib';
import { extrairTextoDocumento } from '../src/lib/documentos-extrair';
import { fragmentarTexto } from '../src/lib/documentos-formatos';
import { descarregarDocumento,linkDocumento,validarLinkDocumento,conhecimentoDocumentos } from '../src/lib/documentos';
import { POST as criar } from '../app/api/admin/documentos/route';
import { PUT as parte,POST as concluir,PATCH as publicar,DELETE as apagar } from '../app/api/admin/documentos/[id]/route';
import { POST as listar } from '../app/api/consultor/documentos/route';
nextEnv.loadEnvConfig(process.cwd());if(!process.env.DATABASE_URL) nextEnv.loadEnvConfig('..',false,console,true);
const sql=neon(process.env.DATABASE_URL!,{fullResults:true});
neonConfig.webSocketConstructor=WebSocket;
const sockets=new NeonPool({connectionString:process.env.DATABASE_URL});
Object.assign(db(),{query:(texto:string,params:unknown[])=>sql.query(texto,params),connect:()=>sockets.connect()});
const req=(url:string,method:string,body:unknown)=>new Request('http://localhost'+url,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
let id:string|undefined;
async function main(){
  const pdf=await PDFDocument.create();pdf.addPage().drawText('Support with your upline. Conversation and confidence.');
  const pdfBytes=await pdf.save();
  assert.match(await extrairTextoDocumento('test.pdf',pdfBytes.slice()),/Support with your upline/);
  const bytes=new Uint8Array(1048576+137);bytes.fill(32);bytes.set(pdfBytes);
  const zip=(await import('jszip')).default;const ppt=new zip();ppt.file('ppt/slides/slide1.xml','<a:t>Ouvir &amp; apoiar</a:t>');
  assert.equal(await extrairTextoDocumento('test.pptx',await ppt.generateAsync({type:'uint8array'})),'Ouvir & apoiar');
  assert(fragmentarTexto('a'.repeat(4000)).length===3);
  assert.equal((await criar(req('/api/admin/documentos','POST',{nome:'test.html',titulo:'x',categoria:'x',descricao:'',tamanho:1}))).status,400);
  const res=await criar(req('/api/admin/documentos','POST',{nome:'teste-documentos.pdf',titulo:'Teste automático documentos',categoria:'Teste temporário',descricao:'',tamanho:bytes.length}));
  assert.equal(res.status,200);id=(await res.json()).id;const ctx={params:Promise.resolve({id:id!})};
  assert.equal((await concluir(req('','POST',{texto:'x'}),ctx)).status,400);
  assert.equal((await parte(new Request('http://localhost/?parte=0',{method:'PUT',body:bytes.slice(0,1048576) as BodyInit}),ctx)).status,200);
  assert.equal((await concluir(req('','POST',{texto:'x'}),ctx)).status,400);
  assert.equal((await parte(new Request('http://localhost/?parte=1',{method:'PUT',body:bytes.slice(1048576) as BodyInit}),ctx)).status,200);
  const texto='Convite: ouvir antes de responder; pedir apoio ao upline. Conversation and confidence.';
  assert.equal((await concluir(req('','POST',{texto}),ctx)).status,200);
  const [row]=(await sql.query('select conhecimento_estado from documentos where id=$1',[id])).rows;
  assert.equal(row!.conhecimento_estado,'indexado');
  const link=linkDocumento(id!);assert(validarLinkDocumento(id!,new URL('http://localhost'+link)));
  const adulterado=new URL('http://localhost'+link);adulterado.searchParams.set('token','0'.repeat(64));assert(!validarLinkDocumento(id!,adulterado));
  assert(!validarLinkDocumento(id!,new URL('http://localhost'+link.replace(/token=./,'token=f').replace(/exp=\d+/,'exp=1'))));
  const full=await descarregarDocumento(id!,new Request('http://localhost/'));assert.equal(full.status,200);
  assert.deepEqual(new Uint8Array(await full.arrayBuffer()),bytes);
  const range=await descarregarDocumento(id!,new Request('http://localhost/',{headers:{range:'bytes=7-31'}}));assert.equal(range.status,206);assert.deepEqual(new Uint8Array(await range.arrayBuffer()),bytes.slice(7,32));
  const cruzado=await descarregarDocumento(id!,new Request('http://localhost/',{headers:{range:'bytes=1048570-1048590'}}));assert.deepEqual(new Uint8Array(await cruzado.arrayBuffer()),bytes.slice(1048570,1048591));
  assert.equal((await descarregarDocumento(id!,new Request('http://localhost/',{headers:{range:'bytes=99999999-'}}))).status,416);
  assert.match(await conhecimentoDocumentos('Tenho receio de fazer um convite'),/upline/);
  assert.equal((await listar(req('','POST',{email:'documentos-nao-existe@example.com'}))).status,403);
  const conta=await listar(req('','POST',{email:'zmrlopes@gmail.com'}));assert.equal(conta.status,200);assert((await conta.json()).documentos.some((d:{id:string})=>d.id===id));
  assert.equal((await publicar(req('','PATCH',{publicado:false}),ctx)).status,200);
  assert.equal((await descarregarDocumento(id!,new Request('http://localhost/'))).status,404);
  assert.equal((await descarregarDocumento(id!,new Request('http://localhost/'),true)).status,200);
  console.log('OK: PDF e PPTX, validação de formatos, upload incompleto/completo, conhecimento, acesso da conta de testes, tokens, download integral, intervalos e ocultação.');
}
main().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{if(id) await apagar(new Request('http://localhost/'),{params:Promise.resolve({id})});await sockets.end();await fecharDb();});
